# Generated by ariadne-codegen on 2024-06-14 12:52
# Source: queries.graphql

from typing import List
from uuid import UUID

from .base_model import BaseModel


class GetEngagementPerson(BaseModel):
    engagements: "GetEngagementPersonEngagements"


class GetEngagementPersonEngagements(BaseModel):
    objects: List["GetEngagementPersonEngagementsObjects"]


class GetEngagementPersonEngagementsObjects(BaseModel):
    objects: List["GetEngagementPersonEngagementsObjectsObjects"]


class GetEngagementPersonEngagementsObjectsObjects(BaseModel):
    employee: List["GetEngagementPersonEngagementsObjectsObjectsEmployee"]


class GetEngagementPersonEngagementsObjectsObjectsEmployee(BaseModel):
    uuid: UUID


GetEngagementPerson.update_forward_refs()
GetEngagementPersonEngagements.update_forward_refs()
GetEngagementPersonEngagementsObjects.update_forward_refs()
GetEngagementPersonEngagementsObjectsObjects.update_forward_refs()
GetEngagementPersonEngagementsObjectsObjectsEmployee.update_forward_refs()
