# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Any

from fastapi import FastAPI
from fastramqpi.main import FastRAMQPI

from calculate_primary import events
from calculate_primary.config import _Settings
from calculate_primary.main import _setup_updater
from calculate_primary.autogenerated_graphql_client import GraphQLClient


def create_app(**kwargs: Any) -> FastAPI:
    settings = _Settings(**kwargs)
    fastramqpi = FastRAMQPI(
        application_name="calculate_primary",
        settings=settings.fastramqpi,
        graphql_version=22,
        graphql_client_cls=GraphQLClient,
    )
    updater = _setup_updater(
        settings.integration,
        settings.dry_run,
        settings.fastramqpi.mo_url,
        settings.eng_types_primary_order,
    )
    fastramqpi.add_context(settings=settings, updater=updater)

    # MO AMQP
    mo_amqp_system = fastramqpi.get_amqpsystem()
    mo_amqp_system.router.registry.update(events.router.registry)

    return fastramqpi.get_app()
